### ISSUE TITLE
Avoid 'Unlikely argument type for equals()' warnings in unit test for entity classes

### ISSUE THREAD

**Issue by uwesinha** [pro-vision/pv-entitygenerator#5]
A while ago, starting with Release 4.7, Eclipse introduced a new type of warning, ["Unlikely argument type"](https://www.eclipse.org/eclipse/news/4.7/M6/#unlikely-argument-types). 

Now Eclipse issues this warning for each unit test class containing tests for entity classes. The offending line can be found in the `testEquals()` method generated for each entity:
https://github.com/pro-vision/pv-entitygenerator/blob/08c209c793e7cbb5f5a1776dd548b7bad4b9199f/PVEntityGenerator/xml/Platform_Java5JPA/entity_entity_unittest-class.xsl#L738

While Eclipse gives these warnings only lowest severity (Info), they still unnecessarily clog up the _Problems_ view. Personally, I don't see much of a point in testing that an entity object is not equal to a constant string value, Thus, I'd suggest to either remove this assertion completely or at least add a `@SuppressWarnings("unlikely-arg-type")` annotation to the `testEquals()` method .

**Comment by uwesinha** [comment]
@stefanseifert: please check my PR.

**Comment by stefanseifert** [comment]
thanks, PR merged
